name: configurable_expansion_tile_null_safety
description: A Configurable Expansion Tile edited from the flutter material implementation that allows for customization
version: 3.2.0
homepage: https://github.com/mdddj/configurable_expansion_tile

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
